import * as T from './three.module.min.js';
import {ApproachEngine,defaults,sanitize} from './engine.js';
import {presets,makeScene} from './scenes.js';
const $=id=>document.getElementById(id),canvas=$('scene'),viewport=$('viewport');
let renderer,world,engine,kind='lab',p={...defaults,...presets.lab},camera=new T.PerspectiveCamera(68,1,.003,300);
let frames=[],samples=[],last=0,lastUI=0,readyMs=null,runStarted=null,stalls=0,history=[],baseSpeed=3,lastDraw=0,lastRAF=0;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const controls=[['speed','速度（単位/秒）',.1,20,.1],['acceleration','加速度（単位/秒²）',0,6,.1],['distance','初期距離（単位）',5,100,1],['size','対象のサイズ倍率',.25,3,.05],['fov','縦の視野角（°）',40,100,1],['height','カメラ高さ（単位）',.02,8,.02],['angle','接近角度（°）',-35,35,1],['gap','表面との余裕（単位）',.02,2,.02]];
for(const [key,label,min,max,step]of controls){const row=document.createElement('div');row.className='parameter';row.innerHTML=`<label for="p-${key}">${label}<input id="p-${key}" type="number" min="${min}" max="${max}" step="${step}" value="${p[key]}"></label>`;$('parameters').append(row);row.querySelector('input').addEventListener('change',e=>{p=sanitize({...p,[key]:+e.target.value});if(key==='speed'){baseSpeed=p.speed;$('pace').value=1;}rebuild();});}
const mobileCourse=document.createElement('label');mobileCourse.innerHTML='接近コース<select id="detail-course"><option value="stop">手前で停止</option><option value="miss">ぎりぎり回避</option><option value="cross">横切る</option><option value="hit">直撃（接触で静止）</option></select>';$('parameters').prepend(mobileCourse);
for(const [id,preset]of Object.entries(presets)){
 let button=document.querySelector(`[data-scene="${id}"]`);if(!button){button=document.createElement('button');button.dataset.scene=id;button.innerHTML=`<span>${preset.en}</span><strong>${preset.name}</strong><small>${preset.tag}</small>`;document.querySelector('.scenarios').append(button);}button.addEventListener('click',()=>selectScene(id));
}
function metricLength(value){const n=value*p.scale;if(n>=1000)return `${(n/1000).toLocaleString('ja-JP',{maximumFractionDigits:1})} km`;if(n<.1)return `${(n*1000).toFixed(1)} mm`;return `${n.toFixed(2)} m`;}
function selectScene(id){kind=id;const mode=p.mode,context=p.context;p={...defaults,...presets[id],mode,context};if($('scale-match').checked)p={...p,height:1,size:1,speed:3,distance:24};baseSpeed=p.speed;$('pace').value=1;rebuild();}
function rebuild(){
 engine?.pause();world?.dispose();p=sanitize(p);world=makeScene($('scale-match').checked?'lab':kind,p);engine=new ApproachEngine(p,world.collider);
 frames=[];samples=[];stalls=0;runStarted=null;lastDraw=0;lastRAF=0;last=performance.now();
 for(const[key]of controls)$(`p-${key}`).value=p[key];$('context').checked=p.context;$('shake').checked=p.shake;$('course').value=p.mode;$('detail-course').value=p.mode;
 document.querySelectorAll('[data-scene]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.scene===kind)));
 const preset=presets[kind];$('scenario-title').textContent=preset.title;$('scenario-description').textContent=preset.description;$('scene-label').textContent=($('scale-match').checked?'比率を揃えた球体 / ':'')+preset.name;
 $('scale-label').textContent=`${kind==='space'?'中心軸から':'視点の高さ'} ${metricLength(p.height)}`;$('overlay-title').textContent=$('scale-match').checked?'同じ比率、違うスケール。':preset.ready;$('overlay-text').textContent=reduced?'動く映像です。スタートで移動、いつでも一時停止。':preset.hint+' 不快なら一時停止を。';$('overlay-kicker').textContent='READY TO APPROACH';$('overlay').hidden=false;$('rating').value='';$('pace-value').textContent=Number($('pace').value)===1?'標準':`${$('pace').value} 倍`;
 camera.fov=p.fov;camera.updateProjectionMatrix();resize();draw();syncButtons();updateUI();
}
function resize(){if(!renderer)return;const r=viewport.getBoundingClientRect();renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();draw();}
function draw(){if(!world||!renderer||!engine)return;camera.position.set(...engine.pos);if(p.shake&&engine.state==='running'&&!reduced)camera.position.y+=Math.sin(engine.t*8)*.004;camera.rotation.set(0,engine.yaw,0);renderer.render(world.scene,camera);lastDraw=performance.now();}
function syncButtons(){const running=engine.state==='running';$('start').disabled=running;$('start').innerHTML=(engine.state==='paused'?'続きから':engine.state==='finished'?'もう一度':'スタート')+' <span>▶</span>';$('stop').disabled=!running;if($('full-stop'))$('full-stop').textContent=running?'一時停止':engine.state==='paused'?'再開':engine.state==='finished'?'もう一度':'スタート';document.body.dataset.state=engine.state;}
function begin(){if(!engine||!renderer)return;if(engine.state==='finished')rebuild();engine.start();runStarted=performance.now();last=runStarted;lastDraw=0;lastRAF=0;$('overlay').hidden=true;syncButtons();}
function pause(){engine?.pause();syncButtons();updateUI();}
function finish(){syncButtons();$('overlay').hidden=false;$('overlay-kicker').textContent='APPROACH COMPLETE';$('overlay-title').textContent=engine.reason==='passed'?'すぐそばを、通り過ぎる。':engine.reason==='contact'?'接触の瞬間。':'目の前で、止まる。';$('overlay-text').textContent='速度や視点を変えて、もう一度。';history.push(report());if(history.length>20)history.shift();}
function updateUI(){if(!engine)return;const m=engine.metrics;$('distance').textContent=metricLength(m.distance);$('angle').textContent=`${(m.theta*180/Math.PI).toFixed(1)}°`;$('expansion').textContent=`${Math.max(0,m.expansion*180/Math.PI).toFixed(1)}°/s`;const mean=frames.length?frames.reduce((a,b)=>a+b,0)/frames.length:null;$('fps').textContent=mean?`${(1000/mean).toFixed(0)} fps`:'—';$('state').textContent={ready:'準備完了',running:'接近中',paused:'一時停止',finished:'体験終了'}[engine.state];$('progress').style.width=`${Math.min(100,100*engine.travel/p.distance)}%`;if(document.querySelector('.diagnostics').open){const r=report();delete r.samples;$('diagnostics').textContent=JSON.stringify(r,null,2);}}
function report(){const sorted=[...frames].sort((a,b)=>a-b);return {scenario:kind,state:engine?.state,parameters:p,normalizedComparison:$('scale-match').checked,elapsedSeconds:engine?.t,metrics:engine?.metrics,performance:{sampleFrames:frames.length,meanFPS:frames.length?1000/(frames.reduce((a,b)=>a+b,0)/frames.length):null,p95FrameMs:sorted.length?sorted[Math.floor((sorted.length-1)*.95)]:null,slowFramesOver50ms:stalls,jsHeapMB:performance.memory?performance.memory.usedJSHeapSize/1048576:null,rendererGeometries:renderer?.info.memory.geometries,rendererTextures:renderer?.info.memory.textures,drawCalls:renderer?.info.render.calls,triangles:renderer?.info.render.triangles,readyMs,pixelRatio:renderer?.getPixelRatio(),viewport:[viewport.clientWidth,viewport.clientHeight],userAgent:navigator.userAgent},rating:$('rating').value||null,samples:[...samples]};}
function frame(now){requestAnimationFrame(frame);const dt=(now-last)/1000;last=now;if(engine?.state!=='running'||document.hidden)return;
 if(lastRAF){const ms=now-lastRAF;frames.push(ms);if(frames.length>1200)frames.shift();if(ms>50)stalls++;}lastRAF=now;
 const before=engine.state;engine.step(dt);draw();if(now-lastUI>200){lastUI=now;samples.push({t:engine.t,...engine.metrics});if(samples.length>1000)samples.shift();updateUI();}if(before==='running'&&engine.state==='finished'){finish();updateUI();}
}
$('start').addEventListener('click',begin);$('stop').addEventListener('click',pause);$('reset').addEventListener('click',rebuild);
for(const id of ['course','detail-course'])$(id).addEventListener('change',e=>{p.mode=e.target.value;rebuild();});
$('pace').addEventListener('input',e=>{$('pace-value').textContent=Number(e.target.value)===1?'標準':`${e.target.value} 倍`;});$('pace').addEventListener('change',e=>{p.speed=baseSpeed*Number(e.target.value);rebuild();});
$('context').addEventListener('change',e=>{p.context=e.target.checked;world.context.visible=p.context;draw();});$('shake').addEventListener('change',e=>{p.shake=e.target.checked;});$('scale-match').addEventListener('change',()=>selectScene(kind));
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});document.addEventListener('keydown',e=>{if(e.code==='Escape'){pause();viewport.classList.remove('expanded');}if(e.code==='Space'&&!['INPUT','SELECT','BUTTON','SUMMARY'].includes(document.activeElement.tagName)){e.preventDefault();engine.state==='running'?pause():begin();}});
$('fullscreen').addEventListener('click',async()=>{if(document.fullscreenElement){pause();await document.exitFullscreen();}else if(viewport.classList.contains('expanded')){pause();viewport.classList.remove('expanded');}else{try{await viewport.requestFullscreen();}catch{viewport.classList.add('expanded');}}resize();});
document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'全画面を閉じる':'全画面 ↗';resize();});
// Keep a stop control reachable in fullscreen, where the side panel is absent.
const fullStop=document.createElement('button');fullStop.id='full-stop';fullStop.textContent='スタート';fullStop.style.pointerEvents='auto';fullStop.addEventListener('click',()=>{if(engine.state==='running')pause();else begin();});document.querySelector('.scene-top').append(fullStop);
document.querySelector('.diagnostics').addEventListener('toggle',updateUI);
$('export').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({current:report(),history},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`shiten-${kind}-${Date.now()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();pause();$('overlay').hidden=false;$('overlay-title').textContent='描画を中断しました';$('overlay-text').textContent='ページを再読み込みしてください。';$('start').disabled=true;});
try{renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1;rebuild();readyMs=performance.now();new ResizeObserver(resize).observe(viewport);requestAnimationFrame(frame);}catch(error){$('overlay-title').textContent='3D描画を開始できません';$('overlay-text').textContent='WebGL2対応ブラウザで、グラフィックアクセラレーションを有効にしてください。';$('start').disabled=true;$('diagnostics').textContent=String(error);}
// Read-only diagnostics plus a bounded development configuration hook for repeatable QA.
window.approachLab={get report(){return report();},get engine(){return engine;},get camera(){return camera;},configure(config){p=sanitize({...p,...config});rebuild();},select:selectScene,start:begin,pause,reset:rebuild};
