import * as T from './three.module.min.js';
import {OsakaRouteEngine,geographic} from './osaka-engine.js';
import {OsakaStream} from './osaka-stream.js';
import {buildChunk} from './osaka-mesh.js';
const $=id=>document.getElementById(id),canvas=$('scene'),viewport=$('viewport');
let renderer,scene,camera,engine,stream,manifest,dirty=true,last=0,lastPlan=0,lastUI=0,lastFrame=0,frames=[],samples=[],startS=0,readyMs=0,initError=null,peakHeap=0,longFrames=0;
const checkpoints=()=>manifest.route.checkpoints;
function resize(){if(!renderer)return;const r=viewport.getBoundingClientRect();renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<700?1.25:1.5));renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();dirty=true;}
function reset(){if(!engine)return;let place=checkpoints().find(c=>c.id===$('start-place').value),dir=Number($('direction').value);if(place.id==='namba'&&dir<0){place=checkpoints().at(-1);$('start-place').value='umeda';}else if(place.id==='umeda'&&dir>0){place=checkpoints()[0];$('start-place').value='namba';}engine.direction=dir;startS=place.s;engine.reset(startS);engine.height=Number($('height').value);engine.kmh=Number($('speed').value);frames=[];samples=[];lastFrame=0;longFrames=0;$('overlay').hidden=false;$('overlay-kicker').textContent='REAL STREETS / REAL SCALE';$('overlay-title').textContent=`${place.name}から、${dir>0?'梅田':'難波'}へ。`;$('overlay-text').textContent='実在の街を進みます。不快ならすぐ一時停止を。';stream.update(engine);dirty=true;sync();}
function start(){if(!engine||stream.workerError)return;if(engine.state==='finished')reset();if(engine.state==='ready'&&!stream.startReady(engine))return;engine.start();last=performance.now();lastFrame=0;$('overlay').hidden=true;updateUI();}
function pause(){engine?.pause();lastFrame=0;updateUI();}
function sync(){if(!engine)return;const running=engine.state==='running',ready=(engine.state!=='ready'||stream.startReady(engine))&&!stream.workerError;$('start').disabled=running||!ready;$('start').textContent=!ready?'周辺を準備中':engine.state==='paused'?'続きから ▶':engine.state==='finished'?'もう一度 ▶':'スタート ▶';$('stop').disabled=!running;$('quick-stop').disabled=!ready&&!running;$('quick-stop').textContent=running?'一時停止':!ready?'準備中':engine.state==='paused'?'再開':'スタート';}
function report(){const f=[...frames].sort((a,b)=>a-b),p=engine?.sample();return{version:'osaka-0.1',sourceTimestamp:manifest?.sourceTimestamp,state:engine?.state,routeMetres:engine?.total,routePositionMetres:engine?.s,heightMetres:engine?.height,speedKmh:engine?.kmh,elapsedSeconds:engine?.elapsed,travelMetres:engine?.travel,coordinates:p?geographic(manifest,p):null,performance:{meanFPS:frames.length?1000/(frames.reduce((a,b)=>a+b,0)/frames.length):null,p95FrameMs:f.length?f[Math.floor((f.length-1)*.95)]:null,longFramesOver50ms:longFrames,readyMs,jsHeapMB:performance.memory?.usedJSHeapSize/1048576||null,peakJsHeapMB:peakHeap||null,drawCalls:renderer?.info.render.calls,triangles:renderer?.info.render.triangles,geometryCount:renderer?.info.memory.geometries,pixelRatio:renderer?.getPixelRatio(),viewport:[viewport.clientWidth,viewport.clientHeight]},stream:stream?.report,samples,userAgent:navigator.userAgent,error:initError};}
function updateUI(){if(!engine)return;const r=report(),v=engine.state==='running'?engine.kmh:0;$('hud-speed').textContent=v;$('speed-readout').textContent=`${v} km/h`;$('height-readout').textContent=`${engine.height} m`;$('distance').textContent=`${Math.round(engine.travel).toLocaleString()} m`;$('fps').textContent=r.performance.meanFPS?`${r.performance.meanFPS.toFixed(0)} fps`:'—';$('coordinates').textContent=`${r.coordinates.lat.toFixed(6)}, ${r.coordinates.lon.toFixed(6)}`;$('chunks').textContent=`${r.stream.loaded} / ${r.stream.wanted} 区画`;$('prefetch').textContent=`前方1,050m · ${r.stream.pending} 件処理中`;$('objects').textContent=`${r.performance.drawCalls} / ${r.performance.triangles?.toLocaleString()}`;
 const near=checkpoints().reduce((a,b)=>Math.abs(a.s-engine.s)<Math.abs(b.s-engine.s)?a:b);$('place').textContent=`${near.name} / ${engine.direction>0?'北へ':'南へ'}`;document.querySelectorAll('[data-station]').forEach(e=>e.classList.toggle('passed',engine.direction>0?Number(e.dataset.station)<=engine.s:Number(e.dataset.station)>=engine.s));$('progress').style.width=`${100*engine.s/engine.total}%`;
 $('city-status').textContent=stream.workerError?'描画処理エラー：再読み込みしてください':r.stream.failed?'一部の街データを取得できません':!stream.coverage(engine)?'街データ読み込み中 / 道路上を継続':engine.state==='running'?'走行中':engine.state==='finished'?'到着':engine.state==='paused'?'一時停止':'準備完了';
 $('performance-note').textContent=`受信 ${(r.stream.bytes/1048576).toFixed(2)} MB / 破棄 ${r.stream.evicted} 区画 / 最大保持 ${r.stream.peakChunks} 区画 / 未読区画上の描画 ${r.stream.missingFrames} フレーム / JSヒープ ${r.performance.jsHeapMB?.toFixed(1)??'計測不可'} MB。前方先読みを優先し、通信待ちで移動を止めません。`;sync();
}
function frame(now){requestAnimationFrame(frame);const dt=(now-last)/1000;last=now;
 if(engine&&engine.state==='running'&&!document.hidden){if(lastFrame){const ms=now-lastFrame;frames.push(ms);if(frames.length>7200)frames.shift();if(ms>50)longFrames++;}lastFrame=now;engine.step(dt);dirty=true;if(!stream.coverage(engine))stream.stats.missingFrames++;if(engine.state==='finished'){$('overlay').hidden=false;$('overlay-kicker').textContent='ROUTE COMPLETE';$('overlay-title').textContent='大阪を、走り抜けた。';$('overlay-text').textContent='高さや速度を変えて、同じ街をもう一度。';sync();}}
 if(engine&&now-lastPlan>250){lastPlan=now;stream.update(engine);}
 if(engine&&dirty&&!document.hidden){const p=engine.sample();camera.position.set(p[0],engine.height+.065,p[1]);camera.rotation.set(0,engine.yaw,0);renderer.render(scene,camera);dirty=false;}
 if(engine&&now-lastUI>500){lastUI=now;peakHeap=Math.max(peakHeap,performance.memory?.usedJSHeapSize/1048576||0);if(engine.state==='running'){samples.push({s:Math.round(engine.s),t:engine.elapsed,...stream.report,drawCalls:renderer.info.render.calls,geometryCount:renderer.info.memory.geometries});if(samples.length>400)samples.shift();}updateUI();}
}
function routeFallback(){
 // Tiny always-resident road strip follows exactly the same OSM nodes; no invented shortcuts.
 const lines=manifest.route.points.slice(1).map((p,i)=>({p:[manifest.route.points[i],p],kind:'road',w:7,main:true,foot:false,layer:0,name:'御堂筋'}));const built=buildChunk({origin:[0,0],buildings:[],areas:[],lines});
 for(const key of ['ground','detail']){const g=new T.BufferGeometry();for(const name of ['position','normal','color'])g.setAttribute(name,new T.BufferAttribute(built[key][name],3));g.computeBoundingSphere();const mesh=new T.Mesh(g,new T.MeshLambertMaterial({vertexColors:true,side:T.DoubleSide}));mesh.position.y=-.015;scene.add(mesh);}
}
$('start').addEventListener('click',start);$('stop').addEventListener('click',pause);$('quick-stop').addEventListener('click',()=>engine?.state==='running'?pause():start());$('reset').addEventListener('click',reset);
for(const id of ['start-place','direction'])$(id).addEventListener('change',()=>{if(id==='start-place'){if($('start-place').value==='umeda')$('direction').value='-1';if($('start-place').value==='namba')$('direction').value='1';}reset();});
$('height').addEventListener('change',()=>{engine.height=Number($('height').value);dirty=true;updateUI();});$('speed').addEventListener('change',()=>{engine.kmh=Number($('speed').value);updateUI();});
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});document.addEventListener('keydown',e=>{if(e.code==='Escape'){pause();viewport.classList.remove('expanded');}if(e.code==='Space'&&!['INPUT','SELECT','BUTTON','SUMMARY'].includes(document.activeElement.tagName)){e.preventDefault();engine?.state==='running'?pause():start();}});
$('fullscreen').addEventListener('click',async()=>{if(document.fullscreenElement){pause();await document.exitFullscreen();}else if(viewport.classList.contains('expanded')){pause();viewport.classList.remove('expanded');}else{try{await viewport.requestFullscreen();}catch{viewport.classList.add('expanded');}}resize();});document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'閉じる':'全画面 ↗';resize();});
$('export').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(report(),null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`shiten-osaka-${Date.now()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();pause();initError='WebGL context lost';$('overlay').hidden=false;$('overlay-title').textContent='描画を中断しました';$('overlay-text').textContent='ページを再読み込みしてください。';});
try{
 renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;scene=new T.Scene();scene.background=new T.Color('#b0c8cf');scene.fog=new T.Fog('#b0c8cf',400,1100);scene.add(new T.HemisphereLight(0xd3e8fa,0x767364,2.2));const sun=new T.DirectionalLight(0xffeed8,2.5);sun.position.set(-700,1000,500);scene.add(sun);camera=new T.PerspectiveCamera(72,1,.025,1250);
 const r=await fetch('./osaka/manifest.json');if(!r.ok)throw Error(`manifest HTTP ${r.status}`);manifest=await r.json();engine=new OsakaRouteEngine(manifest.route);
 const floor=new T.Mesh(new T.PlaneGeometry(12000,12000),new T.MeshLambertMaterial({color:'#6c706b'}));floor.rotation.x=-Math.PI/2;floor.position.y=-.04;scene.add(floor);routeFallback();
 $('stations').replaceChildren(...checkpoints().map(c=>{const span=document.createElement('span');span.dataset.station=c.s;span.textContent=c.name;return span;}));
 stream=new OsakaStream(manifest,scene,()=>{dirty=true;if(!readyMs&&stream.startReady(engine))readyMs=performance.now();sync();});resize();new ResizeObserver(resize).observe(viewport);reset();requestAnimationFrame(frame);
}catch(e){initError=String(e);$('overlay-title').textContent='街を読み込めませんでした';$('overlay-text').textContent='通信とWebGL2対応を確認し、ページを再読み込みしてください。';$('city-status').textContent=initError;}
window.osakaLab={get report(){return report();},get engine(){return engine;},get stream(){return stream;},get camera(){return camera;},start,pause,reset};
