import assert from 'node:assert/strict';import fs from 'node:fs';import zlib from 'node:zlib';
import {OsakaRouteEngine,planChunks,geographic}from './osaka-engine.js';import {buildChunk}from './osaka-mesh.js';
const manifest=JSON.parse(fs.readFileSync(new URL('./osaka/manifest.json',import.meta.url))),raw=JSON.parse(zlib.gunzipSync(fs.readFileSync(new URL('./osaka/source.json.gz',import.meta.url))));
const ways=new Map(raw.elements.filter(e=>e.type==='way').map(e=>[e.id,e]));
for(let i=0;i<manifest.route.wayIds.length;i++){const way=ways.get(manifest.route.wayIds[i]),a=manifest.route.nodeIds[i],b=manifest.route.nodeIds[i+1],j=way.nodes.indexOf(a);assert.ok(way.nodes[j-1]===b||way.nodes[j+1]===b,'Every route edge is an existing consecutive pair of OSM nodes');const coords=geographic(manifest,manifest.route.points[i]);assert.ok(Math.abs(coords.lat-way.geometry[j].lat)<.0000001);assert.ok(Math.abs(coords.lon-way.geometry[j].lon)<.0000001);}
const e=new OsakaRouteEngine(manifest.route);assert.ok(e.total>4200&&e.total<4210);e.start();for(let i=0;i<600;i++)e.step(1/60);assert.ok(Math.abs(e.travel-300/3.6*10)<.001);e.pause();const s=e.s;e.step(1);assert.equal(e.s,s);
for(const direction of [1,-1]){e.direction=direction;e.reset(direction>0?0:e.total);e.start();e.step(0);e.step(-.002);assert.equal(e.state,'running','First frame with zero/negative delta must not finish at departure');let frames=0;while(e.state==='running'&&frames++<5000)e.step(1/60);assert.equal(e.state,'finished');assert.ok(Math.abs(e.travel-e.total)<.001);}
let maxPlan=0;for(let s=0;s<e.total;s+=25){e.reset(s);for(const direction of [-1,1]){e.direction=direction;const plan=planChunks(manifest,e);maxPlan=Math.max(maxPlan,plan.length);assert.ok(plan.length<=48);const p=e.sample(),id=`${Math.floor(p[0]/250)}_${Math.floor(p[1]/250)}`;assert.ok(plan.some(t=>t.id===id),'Current chunk must be included');}}
let triangles=0;for(const tile of manifest.tiles){const data=JSON.parse(fs.readFileSync(new URL(`./osaka/${tile.id}.json`,import.meta.url))),g=buildChunk(data);for(const key of ['near','far','ground','detail']){assert.equal(g[key].position.length,g[key].normal.length);assert.ok(g[key].position.every(Number.isFinite));triangles+=g[key].position.length/9;}}
console.log(JSON.stringify({result:'PASS',routeEdges:manifest.route.wayIds.length,routeMetres:e.total,tiles:manifest.tiles.length,maxPlan,allLodTriangles:triangles,checks:['OSM route-edge provenance','coordinates round trip','300km/h physical displacement','pause invariant','both directions reach endpoint','bounded chunk plans','all tile meshes finite']}));
